### ISSUE TITLE
Extra keys not alowed when pressing complete.

### ISSUE THREAD

**Issue by denko81** [isabellaalstrom/lovelace-grocy-tasks-card#2]
I found extra keys not alowed error when pressing complete but i also found the solution, removing row 131 and 132 from _grocy-tasks-card.js_.

**Comment by LGGGreg** [comment]
Same issue, same solution.  Did you find a better fix?

**Comment by trunks403** [comment]
Same issue, same solution. Thanks for the solution 👍
